### ISSUE TITLE
North-facing switch socket interference

### ISSUE THREAD

**Issue by powwu** [system76/launch#14]
Hello there!

This is just to let you know that, whether intentional or not, your board uses north facing switch sockets. This is not an issue with the included XDA profile caps, but when you switch in aftermarket caps, such as Cherry profile keycaps, [interference is possible](https://youtu.be/pFySgr0xmPw). This causes muffled sound and a bottom-out that feels mushy and uneven. Usually, north facing switch sockets are there to provide better RGB lighting when a key is "backlit" (transparent legending), but this is not the case here. This is a decently significant issue, because Cherry profile keycaps are the most popular among aftermarket keycaps. If you do a revision in the future, I recommend making your switch sockets south-facing.

**Comment by jackpot51** [comment]
We have not seen (heard?) any such issue, and have used other keycaps in testing. I think the way the switch is plate mounted is pretty important

**Comment by lennihein** [comment]
The issue exists, and is widely known by people that ever had any interest in keyboards. A design choice that doesn't make me very confident in the overall process of designing this board.

**Comment by VinnyCordeiro** [comment]
> A design choice that doesn't make me very confident in the overall process of designing this board.

Agreed. I was excited about a new player on the market, specially one that promotes open source solutions like System76, but after taking a look at the design, being a keyboard PCB designer myself, the excitement cooled down significantly. That's unfortunate.

**Comment by leviport** [comment]
To clarify: this is _only_ an issue with Cherry profile's row 4 keycaps. Pretty much all of the other keycap profiles out there (including the XDA caps this board was designed with and will ship with) do not interfere with north-facing switches. 

> but after taking a look at the design, being a keyboard PCB designer myself, the excitement cooled down significantly. That's unfortunate.

Thanks for the feedback, but it's not very constructive. Is anything other than the switch orientation a big issue? We can only improve if we know where we went wrong.

**Comment by WatchMkr** [comment]
Thank you for your input. It's appreciated. I am not experiencing interferences issue with cherry profiles. We tested DSA, XDA, Cherry, and VSA. 

https://user-images.githubusercontent.com/3430283/107816382-e8b60480-6d31-11eb-93a3-b1d715d7a25a.MOV

**Comment by lennihein** [comment]
I am quite fond of System76 overall, so I really want this to succeed. Heavily recommend to get a lot of input from both the Linux (user) and Keyboard Enthusiast (experts) communities to create a product that meets the bar.

**Comment by WatchMkr** [comment]
Thanks again. The orientation is intentional. We did not want LEDs shining out from below the lower portion of the keycap.
