### ISSUE TITLE
Feature request:  bluetooth version

### ISSUE THREAD

**Issue by ByteEnable** [system76/launch#18]
Feature request:  bluetooth version.

**Comment by leviport** [comment]
This request lacks information. If you can elaborate, I can reopen this issue.

**Comment by ByteEnable** [comment]
The addition of a Bluetooth controller to the PCB for wireless keyboarding.

**Comment by leviport** [comment]
Ah, a bluetooth version of the keyboard. Sorry, I'm not sure why I had trouble figuring out what you meant. 

Thanks for the suggestion. I don't think the dock functionality is going to work well over bluetooth, and we're past the point of being able to make such major PCB revisions anyway. Perhaps bluetooth can come in future iterations though.

**Comment by ruffsl** [comment]
> Perhaps bluetooth can come in future iterations though.

If one was to modify the current PCB design to include a bluetooth chipset for this functionality, would anyone have some recommendation on chipsets or radio ICs? A vendor with a friendly open source ecosystem for firmware and bluetooth profiles?
