### ISSUE TITLE
Power (USB PD)

### ISSUE THREAD

**Issue by thibaultmol** [system76/launch#20]
How many watts can the keyboard handle to charge a phone for example? Does it have USB PD?

**Comment by jackpot51** [comment]
It does not have USB PD. The wattage delivered depends on the connection to the computer. If it is connected over USB-C, then a phone connected into a downstream USB-C port will be able to use around 15 watts

**Comment by jackpot51** [comment]
A big reason it doesn't have USB-PD, is that computer motherboards do not support being a USB-PD source, and laptops are usually a sink but almost never a source. So it would require an additional AC adapter for full functionality

**Comment by thibaultmol** [comment]
> A big reason it doesn't have USB-PD, is that computer motherboards do not support being a USB-PD source, and laptops are usually a sink but almost never a source. So it would require an additional AC adapter for full functionality

oh, interesting. Hadn't thought of that actually 👍

**Comment by iMonZ** [comment]
> A big reason it doesn't have USB-PD, is that computer motherboards do not support being a USB-PD source, and laptops are usually a sink but almost never a source. So it would require an additional AC adapter for full functionality

Thats sad
but the idea of PD is still really great!
