### ISSUE TITLE
TrackPoint (like Lenovo has) would be great.

### ISSUE THREAD

**Issue by guettli** [system76/launch#21]
I am addicted to a TrackPoint, since it helps me to switch between typing and moving the mouse easily.

It would be great if you could provide something like this.

**Comment by timvisee** [comment]
I agree! Though I'm afraid it won't fit between the mechanical switches without spacing the keys.

**Comment by jackpot51** [comment]
We thought about it, but it was not easy to fit it into the reconfigurable design because it requires the GHB keycaps to have their corners clipped where the trackpoint would go. Additionally, finding trackpoint hardware is not easy

**Comment by gzeronet** [comment]
Couldn't agree any more.
https://github.com/gzeronet/teensy-trackpoint-tmk-keyboard.git
https://github.com/gzeronet/tp60.git
It works for me, hope that can help. :)
