### ISSUE TITLE
ergonomics, split design

### ISSUE THREAD

**Issue by ahillio** [system76/launch#26]
Wow, this looks great.... and with an ergonomical split design I would be cheering with a megaphone at how awesome this is and you are for making it.  Any chance you'll make one that's ergonomically designed?

**Comment by leviport** [comment]
Thanks for the feedback! There aren't plans for that quite yet (we haven't even officially released Launch quite yet), but it's certainly something that could happen in the future. I'm an avid user of the Ergodox, so I would love to be able to work on something like that some day as well.
