### ISSUE TITLE
consider releasing the CAD source files

### ISSUE THREAD

**Issue by EllaBarker** [system76/launch#30]
To keep the opensource/open hardware mindset I would appreciate it if the native CAD files get released beside the STEP ones.

**Comment by jgrano** [comment]
Hi - The Step file is a much cleaner way to view the design/code if that's your thing. Our in house file format is F3D as we use Fusion 360 for design & manufacturing. Using Step is as close to universal as we can get so any can platform can import the design and you can modify as needed. We can easily import that changes as needed based on a Step file.

**Comment by EllaBarker** [comment]
Releasing the STEP is the right decision as any program can import it but offering the native format, in addition, would be beneficial as modifying the native format is a better experience. That's in line with the recommendations from the OSHW: [https://www.oshwa.org/sharing-best-practices/](https://www.oshwa.org/sharing-best-practices/)
Just a simple, generic example: extend the case by 5 mm. With a native format, the only change would be updating the parameter. With step it is much more complicated and the easiest solution might be cut body, move, and inserting the new part in between.

There is software that claims they can convert a step, obj, igs, etc. back to native formats but in most cases, it fails miserably.

**Comment by jgrano** [comment]
Haven't forgotten about this - I am unable to export the full assembly in a *.f3d format due to the distributed nature of the structure. A full step file export is the only option currently. I am pushing up the chassis designs in their native format.
