### ISSUE TITLE
Feature request / bug report: Change USB-A type socket alignment

### ISSUE THREAD

**Issue by mvdkleijn** [system76/launch#36]
## What?
From my perspective, the USB-A sockets are upside down.

## Reasoning
While I was unable to (quickly) find a relevant specification entry with regards to orientation, most reference images for the socket layout have the pin connectors located at the **top** of the socket. The same goes for the practical application on many, if not most or even all laptops. The pin connectors are at the top.

In the current keyboard design, the connector pins are at the bottom. This would force the user to turn around the USB-A type plug in order to insert it into the socket.

Though the orientation would in many cases probably not matter, there are important benefits to have the socket the right way up.

## Example
An important example is to allow for the insertion of a USB-A type security key such as promoted by the likes of Github and Google. Specifically the design of something like the Yubikey.

This would allow a user to insert the security key into the keyboard instead of the lap/desktop. This kind of key works fine on laptops because of the orientation of the USB-A type socket. However, the Launch keyboard's orientation would block a user from touching the confirmation button on the security key.

I hope you will be able to turn around the sockets... even better would be if a socket could be located on the right or left of the keyboard for easier access to the security key when you need to hit the confirmation button. 😄

**Comment by jackpot51** [comment]
It has been impossible to find USB-A connectors that support 3.2 Gen 2 speeds that can be mounted on the same side but have the orientation reversed. To do this would mean pretty considerably increasing the size of the chassis

**Comment by mvdkleijn** [comment]
> It has been impossible to find USB-A connectors that support 3.2 Gen 2 speeds that can be mounted on the same side but have the orientation reversed. To do this would mean pretty considerably increasing the size of the chassis

That's too bad... 😞 😢  Otherwise this would've been perfect. I guess I'll close this issue then.
