### ISSUE TITLE
Please see discussion on keebtalk

### ISSUE THREAD

**Issue by dkrikun** [system76/launch#38]
Just have a look there, ok?

https://www.keebtalk.com/t/system76-open-source-hotswap-mechanical-keyboard/12946

**Comment by mmstick** [comment]
Not worth wasting anyone's time.

**Comment by jackpot51** [comment]
@dkrikun I really don't get how so many people can miss the fucking point so much

**Comment by dkrikun** [comment]
Maybe you could elaborate?

**Comment by jackpot51** [comment]
Sure, though I doubt it will matter. Most of the complaints I see center around the layout and the price.

**Layout**

The layout is specifically designed to minimize changes from the standard layout while introducing several impactful changes that show up on literally no other keyboards. Some mistake this for a lack of research when the exact opposite is true. We experimented heavily with common layouts, including ortholinear, split ortholinear, and staggered. We experimented with the "standard" key sizes, where the left side would line up perfectly, but would also use 1.25, 1.75, and 2.25 size keys. After a ton of prototypes, we arrived at this layout. Our first task was to reduce the number of key sizes, to maximize where keys could be swapped. This led to the left side and right side being uneven, but in a way I think looks good once you actually use the keyboard. We also split the spacebar, to allow both side to be mapped independently, and allow the caps to be swapped with anything else that has a 2U cap. We include tons of extras to ensure most keys can be put most anywhere. Keep in mind, that while enthusiasts don't care if caps are blank, most users do. This is a keyboard we want any of our customers to be able to use.

**Electrical Design**

Some absolute idiot suggested we have 5 USB ports as though it was a dumb idea. We do, but one is for connecting to the PC. So we have two USB-A and two USB-C ports on each side of that central connector to the PC, it is balanced and even and sensible. To have a 4-port 10Gbps USB hub inside a keyboard, certain things have to be done with the electrical layout. Trying to make it "pretty" is a mistake. Our layout is designed to maximize the USB lane integrity, critical for any high speed design. The switches themselves operate at extremely low frequency compared. We are talking 10 GHz compared to 1 KHz, several orders of magnitude lower. So, the switch and LED lines are moved around to make substantial room for ground planes and the important USB lines. It was not auto-routed AT ALL, this was done by hand with a careful consideration for high speed design requirements.

**Price**

Sure, you can have a 75% for less. With a metal chassis, good caps, and good switches you are approaching the Launch price. Throw in an integrated 4-port 10Gbps USB hub, and you won't find anything else available. Make it not integrated, and you still end up around the price we have for this keyboard. Our costs and profit margins are well researched and match those of other keyboards. If anything, we are in a position to outperform them on price in the future, as we have seen incredible demand for this product from our customers.

**Comment by jackpot51** [comment]
Put that reply up on keebtalk because I'm so damn tired of the hate of this product building out of control:

https://www.keebtalk.com/t/system76-open-source-hotswap-mechanical-keyboard/12946/46?u=jackpot51
