### ISSUE TITLE
Failing to flash the Launch keyboard's firmware.

### ISSUE THREAD

**Issue by uncivilgentleman** [system76/launch#47]
Following the documentation I'll link to on the bottom.  I modified the keymap.c file the way I wanted it.  The problem is the instructions to send the new .hex file to the keyboard aren't working.  It compiles just fine but I keep getting the ERROR: Bootloader not found. Trying again in 5s. even after unplugging the keyboard and plugging it back in while holding the ESC key.   The keyboard lights don't turn on but the error persists and nothing gets uploaded to the keyboard.

https://github.com/system76/qmk_firmware/blob/master/keyboards/system76/launch_1/README.md

_I realize this probably isn't the best place to post this problem but I can't find a better place.  All the official social platforms to engage with the company and its community seem to be proprietary social media platforms like Facebook, Twitter, and Telegram. I don't want to be a part of those places._

**Comment by leviport** [comment]
Are you holding Esc while plugging in your Launch? It can be released a couple seconds after Launch is plugged in. Are you doing that while it's cycling that Bootloader not found message?

**Comment by uncivilgentleman** [comment]
yes I'm holding ESC while plugging in the keyboard.  I've also tried different USB ports (Type A and C) on the computer.

**Comment by leviport** [comment]
Hmm, what happens if you hold Fn+Esc instead? If that works, then I'll need to update those instructions.

**Comment by uncivilgentleman** [comment]
That didn't work either.

**Comment by uncivilgentleman** [comment]
I'm on Fedora 34 and not Pop-OS if that matters.   I don't know why it would but I figure I should mention it.

**Comment by leviport** [comment]
QMK isn't at all specific to Pop, so that should still work. What version of `avrdude` do you have installed?

**Comment by uncivilgentleman** [comment]
avrdude 6.3.  Specifically avrdude-6.3-20.fc34.src.rpm

**Comment by leviport** [comment]
I'm also on 6.3. I'm wondering if a udev rule needs to be set or something. I'll spin up F34 on a lab machine and see if I can figure out how to QMK flash my Launch from it.

**Comment by leviport** [comment]
Alright, I was able to get it dfu-programmer to recognize my Launch if I ran the make command with `sudo`. It also first asked me to run `util/qmk_install.sh` again, so I also ran that with `sudo`. Can you give that a try?

**Comment by uncivilgentleman** [comment]
Yup that works!  I thought about doing that several times, should have.

**Comment by leviport** [comment]
Glad to hear it! Not sure why Fedora requires `sudo` for that when Pop doesn't, but I can probably make a note of that in the instructions.

Oh and to address your note about social media platforms, there's also the Pop!\_OS chat where we even have a Launch Keyboard channel. It's a Mattermost instance that we host ourselves, so you can chat with us there without making accounts on social media platforms. You can find it at https://chat.pop-os.org if you're interested.

**Comment by uncivilgentleman** [comment]
Awesome!  Thank you for the help :)
