### ISSUE TITLE
My keyboard does not work

### ISSUE THREAD

**Issue by rpayanm** [system76/launch#61]
My keyboard has been working perfectly for a year. Yesterday it was working fine and today it does not work, I have not hit it or dropped it. I tested it on another computer and it did not work, also I changed the USB cable and it did not work either.
The dmesg command does not show anything when I plug in/off. 
Any thoughts or recommendations?

**Comment by leviport** [comment]
@rpayanm it sounds like you need to open a support ticket. The support team will be able to take care of you. Github issues are for bug tracking, and the support team generally doesn't hang around here often.

Be sure to let them know which cable you're using, whether the RGB LEDs are working, and the OSes of the computers you tested it on.
