### ISSUE TITLE
Split

### ISSUE THREAD

**Issue by michalsapka** [system76/launch#71]
I see that a full size is in the works (nice!). Are there any plans for a split version?

**Comment by leviport** [comment]
We don't have anything to announce publicly about a split design at this time, but I certainly appreciate the enthusiasm! I talked a bit about some of our earlier prototypes, including a split ortholinear design, in this video around 20min in: https://www.youtube.com/watch?v=GkOBxZjzGiY (and some of my own keyboards before that, if you're interested).
