### ISSUE TITLE
Issue updating Launch Heavy firmware from 0.7.103 to 0.7.104

### ISSUE THREAD

**Issue by g-dg** [system76/launch#88]
I'm having an issue updating my Launch Heavy from 0.7.103 to 0.7.104 using fwupd (1.8.14).

It complains about "writing firmware not supported by device" whether I press the unlock key combination before or after running the update, and whether I have anything else plugged into the keyboard's USB hub or not. It still fails if I reset the keyboard's configuration.

I notice that the update message says "Fixes bootloader jump for FWUPD, which should fix some users being unable to install firmware updates." Could this be what is happening, and if so, how do I fix it?

```
$ sudo fwupdmgr update
Devices with no available firmware updates: 
 • Keyboard
 • Keyboard
 • SSD 970 EVO Plus 1TB
 • System Firmware
 • UMC404HD 192k
 • Unifying Receiver
 • WD Blue SA510 2.5 1000GB
╔══════════════════════════════════════════════════════════════════════════════╗
║ Upgrade Launch Heavy Configurable Keyboard (launch heavy 1) from             ║
║ 0.7.103-4038-g223cd2 to 0.7.104-188-g7a655e530b?                             ║
╠══════════════════════════════════════════════════════════════════════════════╣
║ Fixes bootloader jump for FWUPD, which should fix some users being unable    ║
║ to install firmware updates.                                                 ║
║                                                                              ║
║ Launch Heavy Configurable Keyboard (launch heavy 1) and all connected        ║
║ devices may not be usable while updating.                                    ║
╚══════════════════════════════════════════════════════════════════════════════╝
Perform operation? [Y|n]: 
Action Required: To ensure you have physical access, Launch Heavy Configurable Keyboard (launch heavy 1) needs to be manually unlocked. Please press Left Ctrl+Right Ctrl+Esc to unlock and re-run the update.
Writing…                 [***********                            ] Less than one minute remaining…
writing firmware not supported by device
```

**Comment by leviport** [comment]
That does sound like the bug that was fixed by that update. A rather nasty bug, since it makes it more difficult to install the fix. Fortunately there is a way to update via DFU that circumvents fwupd: https://support.system76.com/articles/launch_2-firmware-update

After this update, fwupd will work as expected.

**Comment by g-dg** [comment]
Thanks for pointing me in the right direction. I eventually managed to get it working.

I tried using both an AUR build and a manual build (since the AppImage for the keyboard configurator with the new firmware doesn't seem to be available from the repo releases page). Those failed with a message about `/var/lib/system76-keyboard-configurator/system76_launch_heavy_1_default.hex` missing, so I copied the hex files in the `data` directory of the keyboard configurator source code to that location, but then it failed with a message about the flash not being empty.

Then I looked at the keyboard configurator source code to see if I could find the `dfu-programmer` command. I found it in [src/configurator_app.rs](https://github.com/pop-os/keyboard-configurator/blob/master/src/configurator_app.rs). I then copied the command (make sure it's the correct one for your keyboard!) and added `--force` to bypass the empty flash check. Then, after issuing the flash and reset commands, the keyboard is now on the latest firmware and reinstalling the latest firmware with fwupd now works!

Unfortunately, I found an issue with remapping layer access keys from the factory default in the configurator causing layers to get stuck with the new firmware, but that's an issue for the keyboard-configurator repo. Fortunately holding ESC while plugging in the keyboard resets it nicely.

**Comment by leviport** [comment]
Ah sorry, I just assumed you were on Pop. This can also be done by manually flashing QMK firmware: https://github.com/system76/qmk_firmware/tree/master/keyboards/system76/launch_heavy_1 

We also discovered the configurator issue today, and we have a PR that should fix it open here: https://github.com/pop-os/keyboard-configurator/pull/189 

Turns out this bug has become quite the headache for us here, but I think we're pretty close to putting it all behind us.

**Comment by leviport** [comment]
The latest release also fixes the appimage build: https://github.com/pop-os/keyboard-configurator/releases/tag/v1.3.6

I believe that should square things away, so I'm going to close this. Let me know if there is any more trouble and we can reopen it.
