### ISSUE TITLE
Add music/audio controls

### ISSUE THREAD

**Issue by liam-clink** [system76/launch#94]
A common feature on keyboards is a volume knob, play/pause, and next/previous buttons. This is the primary thing turning me off to buying one of these keyboards, so I hope you implement this, as I love the concept otherwise and want to support it.

**Comment by leviport** [comment]
Launch Heavy has play/pause, previous track, and next track above the tenkey. While it is not bound by default on Launch and Launch Lite, they (as well as volume control keys) can easily be bound with the System76 Keyboard Configurator application: https://github.com/pop-os/keyboard-configurator/

**Comment by liam-clink** [comment]
My main and first point was the volume knob, which it does not have. Having to switch out of a game or something in order to change the volume is quite inconvenient.

**Comment by jacobgkau** [comment]
While it's not a knob (which would add significant manufacturing complexity and would not be as configurable), you can assign Volume Up and Volume Down to any key (or Fn + key) using the Keyboard Configurator. If you do that, you won't have to switch out of a game or move the mouse to adjust the volume.
