### ISSUE TITLE
Monitor not working over usb hub

### ISSUE THREAD

**Issue by boehs** [system76/launch#95]
![HEIC to JPG Conversion](https://github.com/user-attachments/assets/2bf426c2-3c9a-4e88-b660-3836c80fc39e)

Hi, this keyboard is brilliant. The hub works for most things, but my monitor does not work over it. I assume this is some issue with the firmware? It would be awesome if I had one less wire to plug in and out

**Comment by boehs** [comment]
Hm, I've done a little studying and found it may be related to [USB-C alt-mode for video](https://superuser.com/questions/1614732/is-it-possible-to-upgrade-a-basic-usb-c-to-have-usb-c-alternate-mode)? Maybe the USB-C ports in this keyboard don't have it?

**Comment by leviport** [comment]
Launch's integrated USB hub does not support DisplayPort over USB-C. Something like a DisplayLink dock _might_ work, but DisplayLink docks are often not the greatest experience. I suppose they may be better supported on macOS though. I have very little experience with macOS, so I don't know for certain.
